---
abstract: 'Mock Test::* code to succeed or do nothing.'
author:
  - 'Steffen Schwigon, C<< <schwigon at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Deep: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Mock-Test
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.6.1
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Test-Mock-Test
  license: http://dev.perl.org/licenses/
  repository: git://github.com/renormalist/test-mock-test.git
version: 0.01
